language: node_js
node_js:
        - 0.10
before_script:
        - npm install -g grunt-cli
notifications:
        irc:
                channels:
                        - "irc.rizon.net#clearwing"
                on_success: change
                on_failure: change
